services:
  postgres:
    image: postgres:16
    container_name: fs-postgres
    environment:
      POSTGRES_DB: fsdb
      POSTGRES_USER: fsuser
      POSTGRES_PASSWORD: fspass
    ports:
      - "5432:5432"
    volumes:
      - fs_pgdata:/var/lib/postgresql/data

volumes:
  fs_pgdata: