services:
  postgres:
    image: postgres:16
    container_name: fs-postgres
    environment:
      POSTGRES_DB: fsdb
      POSTGRES_USER: fsuser
      POSTGRES_PASSWORD: fspass
    ports:
      - "5432:5432"
    volumes:
      - fs_pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonardb
      SONAR_JDBC_USERNAME: fsuser
      SONAR_JDBC_PASSWORD: fspass
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root 
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube
    privileged: true


volumes:
  fs_pgdata:
  sonarqube_data:
  jenkins_data: